imports:
  - instructions
  # - google_search_tool
  # Server MCP tools don't work with ADK because of a bug when they return objects or something like that.
  # - github_tool
options:
  root_agent:
    # Models: https://ai.google.dev/gemini-api/docs/models
    # agent_model: 'gemini-2.5-flash-lite'
    agent_model: 'gemini-2.5-flash'
